### ISSUE TITLE
Is there a demo script to reproduce your paper's results?

### ISSUE THREAD

**Issue by gauenk** [ckkelvinchan/BasicVSR_PlusPlus#1]

**Comment by ckkelvinchan** [comment]
Hi, you can use MMEditing APIs to reproduce the results: https://mmediting.readthedocs.io/en/latest/quick_run.html#test-a-pre-trained-model

![image](https://user-images.githubusercontent.com/7676947/160310946-a1f75e6e-d42e-45db-9601-2d96533f3786.png)

**Comment by gauenk** [comment]
To run this command on MMEditing I need (1) a config file and (2) a checkpoint file. I do not see this included in the repo.

I would love to be able to reproduce Table 1 in [your paper](https://arxiv.org/pdf/2104.13371.pdf). Maybe you can share the script you used to create the table?

**Comment by ckkelvinchan** [comment]
The checkpoints and configurations can be found [here](https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/basicvsr_plusplus).

**Comment by gauenk** [comment]
Thank you :+1:
