### ISSUE TITLE
denoise pretrained model  didn't work

### ISSUE THREAD

**Issue by bjiale** [ckkelvinchan/BasicVSR_PlusPlus#12]
Hi @ckkelvinchan , I have tried to run the denoise pretrianed model with DAVIS-test dataset, but the result images has no difference between the input images. My experiment is as below:
pretrained model: basicvsr_plusplus_denoise-28f6920c.pth
optical flow model: I download it to my local path
dataset: I use the  the tractor folder in DAIVS-test dataset which is used in your paper. I add the sigma 50 gaussian noise to the pictures as input.
result:
![image](https://user-images.githubusercontent.com/106739374/171635832-e6c8cf29-fd16-4202-8839-00fe2d24c290.png)

It seem that it run successfully, but the result has no change between the input.
 Is their any parameter or option error in my attempt? 
By the way, basicvsr_plusplus_c64n7_8x1_600k_reds4.pth can run successfully and the result is excellent!

**Comment by ckkelvinchan** [comment]
That’s strange. Can you send me the input you used and let me have a try?

**Comment by bjiale** [comment]
My input data.
[tractor.zip](https://github.com/ckkelvinchan/BasicVSR_PlusPlus/files/8842299/tractor.zip)
thanks~

**Comment by ckkelvinchan** [comment]
How did you add the noise? Also, I observed pixel shift when compared with the GT.

**Comment by bjiale** [comment]
I used the RandomNoise function in your code to add the noise.
![image](https://user-images.githubusercontent.com/106739374/172117637-c2583d97-3e17-47b5-a061-da54d54a8b58.png)

**Comment by bjiale** [comment]
About the pixel shift, I crop 2 pixels in width to make the image size can divided by 4.

**Comment by bjiale** [comment]
Is my data's noise type different from the training dataset?

**Comment by ckkelvinchan** [comment]
I guess that's because you saved the frames as `.jpg`, which produces compression. Try saving it to `.png`.

In addition, For frames not divisible by 4, I padded zero at the end (i.e., last rows and columns) and crop it after processing, to make sure there is no pixel shift.

**Comment by bjiale** [comment]
Yes, thank you~ You are right. I try to use png format image and it works!
