### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by linjing7** [ckkelvinchan/BasicVSR_PlusPlus#15]
Hi, thank you very much for your excellent work. I wonder could you please show us the folders of the dataset like the following forms? So that I can recollect the dataset into the same form as yours.
![image](https://user-images.githubusercontent.com/70081899/175857513-9606b7a1-4463-4d21-8cf9-f020adfe3188.png)

**Comment by mate-huaboy** [comment]
> Hi, thank you very much for your excellent work. I wonder could you please show us the folders of the dataset like the following forms? So that I can recollect the dataset into the same form as yours. ![image](https://user-images.githubusercontent.com/70081899/175857513-9606b7a1-4463-4d21-8cf9-f020adfe3188.png)

Hi, What is the folder structure of the dataset? I'm not sure if this issue has been resolved yet. I now also need to organize a dataset to train a model.
