### ISSUE TITLE
How to fix mmcv version incompatible issue on Colab

### ISSUE THREAD

**Issue by b06901089** [ckkelvinchan/BasicVSR_PlusPlus#27]
Hi
I ran the colab notebook and ran into this error.
AssertionError: mmcv==1.7.1 is used but incompatible. Please install mmcv-full>=(1, 3, 13, 0, 0, 0), <=(1, 6, 0, 0, 0, 0).

mmcv version seems to directly related to CUDA version. 
I could not install old version of mmcv-full without countering the "Building wheel for mmcv-full (setup.py) ..." issue.
Is there a way to work around?

Thank you!

**Comment by xeghesoopn** [comment]
also getting this error locally and noticed that mmedit/\_\_init\_\_.py calls for an mmcv version between 1.3.13 and 1.6. updating line 23 of \_\_init\_\_.py to the current mmcv version, 1.7.1, seems not to be immediately catastrophic as far as i can tell

**Comment by b06901089** [comment]
Actually,
Using older version of pytorch(==1.9.0) allows me to install mmcv-full between 1.3.13 and 1.6.
