### ISSUE TITLE
Solution for mmcv on Ubuntu✅

### ISSUE THREAD

**Issue by WAYSC** [ckkelvinchan/BasicVSR_PlusPlus#51]
My cuda version is 11.6, so pytorch verison is 1.13.1, use this to install :
`pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116`
but later the mmcv is incompatible, the hint is: Please install mmcv-full>=[1, 3, 13], <=[1, 6]. so use this:
`pip install mmcv-full==1.6.0`
then you'll be fine! :)

**Comment by zheyicode** [comment]
my solution is a little different, the first step is really useful, but the second fail.
so my solution is "conda install mmcv-full==1.6.0", then the environment built successfully.

**Comment by WAYSC** [comment]
Yeah, they are similar, the first step is out of the reason to correspond my PyTorch with cuda.
But eventually, the inference failed when i use my own video(maybe the solution is a little big), it's out of memory😭 i am trying another model now.
