### ISSUE TITLE
Question for the computation of cond__n1

### ISSUE THREAD

**Issue by jiang-xingbp** [ckkelvinchan/BasicVSR_PlusPlus#9]
why the cond_n1 is the out of flow_wrap(feat_prop, flow_n1.permute(0, 2, 3, 1)) while feat_prop is zeros?
why not  flow_wrap(feat_n1,flow_n1.permute(0, 2, 3, 1) and feat_n1 = feats[module_name][-1]

**Comment by jiang-xingbp** [comment]
Thanks for your reply and i like your work very much, but i still have a question. In this way, computational cost is saved, however, the feature of adjacent frames is not transmitted to the feat-prop,which seems inconsistent with the paper. 
By the way, is the saving of computational cost substantial?

**Comment by ckkelvinchan** [comment]
At `i=0`, there is no neighbouring feature, and therefore you can directly set `feat_prop` to zero. For `i>0`, we need to use `cond_n1` and `cond_n2`to align the neighboring feature

**Comment by jiang-xingbp** [comment]
OHHH,i get it. Sorry, I was sloppy when I looked at the code😂. Thank you very much🤞.
